version: '3'
services:
  app:
    build: .
    restart: always
    container_name: "${APP_NAME}_APP"
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

  job:
    build: .
    restart: always
    container_name: "${APP_NAME}_JOB"
    env_file:
      - .env
    environment:
      - DOCKER_APP=job

